import{a as u,f as b,i as p}from"./assets/vendor-b069HG88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();async function w(a){const o={method:"GET",url:"https://geocoding-by-api-ninjas.p.rapidapi.com/v1/geocoding",params:{city:a},headers:{"x-rapidapi-key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","x-rapidapi-host":"geocoding-by-api-ninjas.p.rapidapi.com","Content-Type":"application/json"}};try{return(await u.request(o)).data}catch(e){console.error(e)}}async function C(a,o){try{const e={method:"get",maxBodyLength:1/0,url:`https://meteostat.p.rapidapi.com/stations/nearby?lat=${a}&lon=${o}&limit=5`,headers:{"X-RapidAPI-Key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","X-RapidAPI-Host":"meteostat.p.rapidapi.com"}};return(await u.request(e)).data}catch(e){return console.error("Ошибка запроса:",e),null}}function I(a){return a.data[0].id}async function S(a,o){try{const e={method:"GET",url:"https://meteostat.p.rapidapi.com/stations/daily",params:{station:a,start:String(o),end:String(o)},headers:{"x-rapidapi-key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","x-rapidapi-host":"meteostat.p.rapidapi.com","Content-Type":"application/json"}};return(await u.request(e)).data}catch(e){return console.error(e),null}}const d=document.querySelector(".result"),c=document.querySelector("body"),q=document.querySelector("#datetime-picker");b(q,{altInput:!0,altFormat:"F j, Y",dateFormat:"Y-m-d",allowInput:!0,disableMobile:!0,onReady(a,o,e){e.altInput.type="text",e.altInput.placeholder="Select a date"}});function x({tmin:a,tmax:o,wspd:e},s,t,r){v(s);const n=`<p class="city-title">
        City: ${j(t)} 
        <img 
            src="https://flagcdn.com/w40/${r.toLowerCase()}.png" 
            alt="flag ${r}" 
            width="24" 
            height="16"
        >
    </p>
    <p class="date">Date: ${s}</p>
    <p class="max-temp">Max temperature: ${o} °C</p>
    <p class="msn-temp">Minimal temperature: ${a} °C</p>
    <p class="windspeed">Average windspeed: ${e} m/s</p>`;d.style.visibility="visible",d.insertAdjacentHTML("beforeend",n)}function L(){d.style.visibility="hidden",d.innerHTML=""}function j(a){return a[0].toUpperCase()+a.slice(1)}function v(a){switch(Number(a.split("-")[1])){case 12:case 1:case 2:return c.className="winter";case 3:case 4:case 5:return c.className="spring";case 6:case 7:case 8:return c.className="summer";case 9:case 10:case 11:return c.className="autumn";default:return"Некорректный месяц"}}const l=document.querySelector(".form"),f=document.querySelector(".submitBtn");l.addEventListener("submit",async a=>{a.preventDefault(),L(),f.disabled=!0;const o=new FormData(l),e=o.get("search-text").trim(),s=o.get("datetime-picker").split(" ")[0];let t=null;if(!(!e&&s))try{const r=await w(e);let n="UA";if(Array.isArray(r)&&r.length>0){const{latitude:y,longitude:h,country:g}=r[0],i=await C(y,h);if(n=g,i&&i.data&&i.data.length>0)t=I(i);else{p.show({message:"Station not found",color:"red",position:"topRight"});return}const m=await S(t,s);if(m.data.length!==0)x(m.data[0],s,e,n);else{p.show({message:"Data not found for this date. Try another.",color:"red",position:"topRight"});return}}else{p.show({message:"City not found",color:"red",position:"topRight"});return}}catch(r){console.error("Ошибка:",r)}finally{l.reset(),f.disabled=!1}});
//# sourceMappingURL=index.js.map
