import{a as u,f as b,i as l}from"./assets/vendor-b069HG88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();async function w(a){const s={method:"GET",url:"https://geocoding-by-api-ninjas.p.rapidapi.com/v1/geocoding",params:{city:a},headers:{"x-rapidapi-key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","x-rapidapi-host":"geocoding-by-api-ninjas.p.rapidapi.com","Content-Type":"application/json"}};try{return(await u.request(s)).data}catch(e){console.error(e)}}async function C(a,s){try{const e={method:"get",maxBodyLength:1/0,url:`https://meteostat.p.rapidapi.com/stations/nearby?lat=${a}&lon=${s}&limit=5`,headers:{"X-RapidAPI-Key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","X-RapidAPI-Host":"meteostat.p.rapidapi.com"}};return(await u.request(e)).data}catch(e){return console.error("Ошибка запроса:",e),null}}function I(a){return a.data[0].id}async function S(a,s){try{const e={method:"GET",url:"https://meteostat.p.rapidapi.com/stations/daily",params:{station:a,start:String(s),end:String(s)},headers:{"x-rapidapi-key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","x-rapidapi-host":"meteostat.p.rapidapi.com","Content-Type":"application/json"}};return(await u.request(e)).data}catch(e){return console.error(e),null}}const q=document.querySelector("#datetime-picker"),d=document.querySelector(".result"),c=document.querySelector("body");b(q,{altInput:!0,altInputClass:"input",dateFormat:"Y-m-d",altFormat:"F j, Y",allowInput:!0,defaultDate:null,onReady:(a,s,e)=>{e.altInput.placeholder="Select date"}});function L({tmin:a,tmax:s,wspd:e},o,t,r){x(o);const n=`<p class="city-title">
        City: ${v(t)} 
        <img 
            src="https://flagcdn.com/w40/${r.toLowerCase()}.png" 
            alt="flag ${r}" 
            width="24" 
            height="16"
        >
    </p>
    <p class="date">Date: ${o}</p>
    <p class="max-temp">Max temperature: ${s} °C</p>
    <p class="msn-temp">Minimal temperature: ${a} °C</p>
    <p class="windspeed">Average windspeed: ${e} m/s</p>`;d.style.visibility="visible",d.insertAdjacentHTML("beforeend",n)}function j(){d.style.visibility="hidden",d.innerHTML=""}function v(a){return a[0].toUpperCase()+a.slice(1)}function x(a){switch(Number(a.split("-")[1])){case 12:case 1:case 2:return c.className="winter";case 3:case 4:case 5:return c.className="spring";case 6:case 7:case 8:return c.className="summer";case 9:case 10:case 11:return c.className="autumn";default:return"Некорректный месяц"}}const p=document.querySelector(".form"),f=document.querySelector(".submitBtn");p.addEventListener("submit",async a=>{a.preventDefault(),j(),f.disabled=!0;const s=new FormData(p),e=s.get("search-text").trim(),o=s.get("datetime-picker").split(" ")[0];let t=null;if(!(!e&&o))try{const r=await w(e);let n="UA";if(Array.isArray(r)&&r.length>0){const{latitude:y,longitude:h,country:g}=r[0],i=await C(y,h);if(n=g,i&&i.data&&i.data.length>0)t=I(i);else{l.show({message:"Station not found",color:"red",position:"topRight"});return}const m=await S(t,o);if(m.data.length!==0)L(m.data[0],o,e,n);else{l.show({message:"Data not found for this date. Try another.",color:"red",position:"topRight"});return}}else{l.show({message:"City not found",color:"red",position:"topRight"});return}}catch(r){console.error("Ошибка:",r)}finally{p.reset(),f.disabled=!1}});
//# sourceMappingURL=index.js.map
