import{a as u,f as g,i as d}from"./assets/vendor-b069HG88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();async function b(s){const o={method:"GET",url:"https://geocoding-by-api-ninjas.p.rapidapi.com/v1/geocoding",params:{city:s},headers:{"x-rapidapi-key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","x-rapidapi-host":"geocoding-by-api-ninjas.p.rapidapi.com","Content-Type":"application/json"}};try{return(await u.request(o)).data}catch(r){console.error(r)}}async function w(s,o){try{const r={method:"get",maxBodyLength:1/0,url:`https://meteostat.p.rapidapi.com/stations/nearby?lat=${s}&lon=${o}&limit=5`,headers:{"X-RapidAPI-Key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","X-RapidAPI-Host":"meteostat.p.rapidapi.com"}};return(await u.request(r)).data}catch(r){return console.error("Ошибка запроса:",r),null}}function C(s){return s.data[0].id}async function L(s,o){try{const r={method:"GET",url:"https://meteostat.p.rapidapi.com/stations/daily",params:{station:s,start:String(o),end:String(o)},headers:{"x-rapidapi-key":"86d5406d44mshecff8b83aef3ec5p1c73d7jsna35665601b9f","x-rapidapi-host":"meteostat.p.rapidapi.com","Content-Type":"application/json"}};return(await u.request(r)).data}catch(r){return console.error(r),null}}const S=document.querySelector("#datetime-picker"),p=document.querySelector(".result"),c=document.querySelector("body");g(S);function q({tmin:s,tmax:o,wspd:r},a,e,t){$(a);const n=`<p class="city-title">
        City: ${x(e)} 
        <img 
            src="https://flagcdn.com/w40/${t.toLowerCase()}.png" 
            alt="flag ${t}" 
            width="24" 
            height="16"
        >
    </p>
    <p class="date">Date: ${a}</p>
    <p class="max-temp">Max temperature: ${o} °C</p>
    <p class="msn-temp">Minimal temperature: ${s} °C</p>
    <p class="windspeed">Average windspeed: ${r} m/s</p>`;p.style.visibility="visible",p.insertAdjacentHTML("beforeend",n)}function v(){p.style.visibility="hidden",p.innerHTML=""}function x(s){return s[0].toUpperCase()+s.slice(1)}function $(s){switch(Number(s.split("-")[1])){case 12:case 1:case 2:return c.className="winter";case 3:case 4:case 5:return c.className="spring";case 6:case 7:case 8:return c.className="summer";case 9:case 10:case 11:return c.className="autumn";default:return"Некорректный месяц"}}const l=document.querySelector(".form");l.addEventListener("submit",async s=>{s.preventDefault(),v();const o=new FormData(l),r=o.get("search-text").trim(),a=o.get("datetime-picker").split(" ")[0];let e=null;if(!(!r&&a))try{const t=await b(r);let n="UA";if(Array.isArray(t)&&t.length>0){const{latitude:f,longitude:y,country:h}=t[0],i=await w(f,y);if(n=h,i&&i.data&&i.data.length>0)e=C(i);else{d.show({message:"Station not found",color:"red",position:"topRight"});return}const m=await L(e,a);if(m.data.length!==0)q(m.data[0],a,r,n);else{d.show({message:"Data not found for this date. Try another.",color:"red",position:"topRight"});return}}else{d.show({message:"City not found",color:"red",position:"topRight"});return}}catch(t){console.error("Ошибка:",t)}finally{l.reset()}});
//# sourceMappingURL=index.js.map
